version: '3.8'

services:
  charger-proxy:
    image: 127.0.0.1:5000/charger-proxy:latest
    ports:
      - "8082:8082"
    environment:
      - PORT=8082
    networks:
      - charger-network
    deploy:
      replicas: 3

  charger-manager:
    image: 127.0.0.1:5000/charger-manager:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - WS_URL=http://charger-proxy:8082/ws
    networks:
      - charger-network
    deploy:
      replicas: 3
      restart_policy:
        condition: any
        delay: 5s
        max_attempts: 3

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_DB=chargerdb
      - POSTGRES_USER=postgrau
      - POSTGRES_PASSWORD=postgrau
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - charger-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

networks:
  charger-network:
    driver: overlay
    attachable: true
