services:
  charger-proxy:
    image: 127.0.0.1:5000/charger-proxy:latest
    ports:
      - "8082:8082"
    env_file:
        - /shared/envs/proxy.env
    networks:
      - charger-network
    deploy:
      replicas: 2
      restart_policy:
        condition: on-failure
        max_attempts: 3
        delay: 10s

networks:
  charger-network:
    external: true
