services:
  db-migrate:
    image: flyway/flyway:10
    env_file:
      - ../envs/db.env
    command: migrate
    networks:
      - charger-network
    volumes:
      - /shared/migrations:/shared/migrations:ro
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      restart_policy:
        condition: none

networks:
  charger-network:
    external: true
