services:
  db-migrate:
    image: flyway/flyway:10
    command:
      - -url=jdbc:postgresql://postgres:5432/chargerdb
      - -user=postgrau
      - -password=postgrau
      - -locations=/shared/migrations/
      - migrate
    networks:
      - charger-network
    deploy:
      replicas: 1
      restart_policy:
        condition: none
