services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    env_file:
        - /shared/envs/db.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - charger-network
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M


networks:
  charger-network:
    external: true

volumes:
  postgres_data:
    driver: local
