//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.12.02 at 04:14:15 AM BRT 
//


package com.ifpb.charger_proxy.schemas;

import javax.xml.namespace.QName;
import jakarta.xml.bind.JAXBElement;
import jakarta.xml.bind.annotation.XmlElementDecl;
import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ifpb.charger_proxy.schemas package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _MessageContent_QNAME = new QName("http://ifpb.com/charger-proxy", "MessageContent");
    private final static QName _MessageId_QNAME = new QName("http://ifpb.com/charger-proxy", "MessageId");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ifpb.charger_proxy.schemas
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MessageResponse }
     * 
     */
    public MessageResponse createMessageResponse() {
        return new MessageResponse();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link String }{@code >}
     */
    @XmlElementDecl(namespace = "http://ifpb.com/charger-proxy", name = "MessageContent")
    public JAXBElement<String> createMessageContent(String value) {
        return new JAXBElement<String>(_MessageContent_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     * 
     * @param value
     *     Java instance representing xml element's value.
     * @return
     *     the new instance of {@link JAXBElement }{@code <}{@link Long }{@code >}
     */
    @XmlElementDecl(namespace = "http://ifpb.com/charger-proxy", name = "MessageId")
    public JAXBElement<Long> createMessageId(Long value) {
        return new JAXBElement<Long>(_MessageId_QNAME, Long.class, null, value);
    }

}
