//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2025.11.30 at 05:07:41 PM BRT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://ifpb.com/charger-proxy", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ifpb.charger_proxy.schemas;
